apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-linux
  labels:
    app: {{ .Release.Name }}-linux
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: linux-demo
      image: {{ printf "%s-linux:%s" .Values.image.repository .Values.image.tag | quote }}
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
